pipeline:
  build:
    image: golang:latest
    commands:
      - go build -o ./app .

  publish:
    image: plugins/docker
    settings:
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      repo: kumar1996/woodpecker
      tags: latest
