pipeline:
  build:
    image: golang:latest
    commands:
      - go build -o ./app .

  publish:
    image: plugins/docker
    settings:
      secrets: [ docker_username, docker_password ]
      repo: kumar1996/woodpecker
      tags: latest
